### ISSUE TITLE
There are no inpainted backgrounds and blurred details.

### ISSUE THREAD

**Issue by Sharpiless** [JeffreyXiang/ivid#6]
Hello, thanks for your great and exciting work!

But i got some strange results using pretrained ckpts:

https://github.com/JeffreyXiang/ivid/assets/50802787/2ae6d103-0f5a-4a3f-9753-2e8742f6f228

https://github.com/JeffreyXiang/ivid/assets/50802787/c846104f-231a-4ef7-90d1-c8e1a5490c3e

Any suggestions?

**Comment by JeffreyXiang** [comment]
It seems that you executed `inference/render.py` with scenes comprising solely of the initial unconditional views.
To generate a complete scene with 27 views, try running `inference/sample.py` with the `3x9` viewset option.
Can you please provide the commands you used? In case this is a bug, I will address it as soon as possible.
Thank you.

**Comment by Sharpiless** [comment]
Thank you for your reply! I ran the following command:
```
python inference/sample.py --num_samples 2 --classes random \
    --viewset uncond --steps_uncond 1000 --steps_cond 50 --guidance 0.5

python inference/render.py \
    --scene_dir samples/imagenet128/viewset_uncond_steps_u1000_c50_guidance0.5/ \
    --output_dir samples/imagenet128/viewset_uncond_steps_u1000_c50_guidance0.5/rendering \
    --frames 60 --traj swing
```

**Comment by Sharpiless** [comment]
Oh i get it. I'll try 3x9 for multi-view generation. Thanks a lot!
